# file_run="/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/train_v1.py"
file_run="/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/train_v2.py"
# file_run="/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/train_v3.py"
# python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v3.3.0.yaml"
# python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v3.3.1.yaml"
# python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v3.3.2.yaml"
# python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v3.3.3.yaml"
# python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v2.6.1_test.yaml"
# python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v2.6.1_test_2.yaml"
# python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v3.3.4.yaml"
python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v3.3.4.1.yaml"
python "$file_run" --config "/home/jovyan/data/aurora/ISO_L2_eye_mouth_blink/eye/train/configs/v3.3.6.yaml"